name: FMCSA Dispatcher

on:
  workflow_dispatch:
    inputs:
      batch_size:
        description: 'How many MCs per batch'
        required: false
        default: '250'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Split mc_list.txt into batches
        run: |
          mkdir -p batches
          split -l ${{ github.event.inputs.batch_size }} mc_list.txt batches/batch_

      - name: Dispatch extractor for each batch
        run: |
          for f in batches/*; do
            echo "Dispatching batch $f"
            gh workflow run extractor.yml -f batch_file=$f
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
